<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IDevelop.Core\IDevelop.Core.csproj" />
    <ProjectReference Include="..\IDevelop.FakeAgent\IDevelop.FakeAgent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
    <None Include="..\Shared\Fixtures\**" LinkBase="Fixtures" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\samples\storage-change\**\*" LinkBase="sample-project" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
