#!/usr/bin/env node
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const usage = 'Usage: node scripts/fluent-icons.mjs [--fetch | --check] [root]';
const args = process.argv.slice(2);
const mode = ['--fetch', '--check'].includes(args[0]) ? args.shift() : 'write';
if (args.length > 1 || args[0]?.startsWith('--')) {
  console.error(usage);
  process.exit(2);
}

const root = resolve(args[0] ?? join(dirname(fileURLToPath(import.meta.url)), '..'));
const manifestFile = join(root, 'scripts', 'icons', 'fluent-icons.json');
const svgFolder = join(root, 'scripts', 'icons', 'fluent');
const desktop = join(root, 'src', 'IDevelop.Desktop');
const output = join(desktop, 'Theme', 'FluentIcons.axaml');
const shown = (path) => relative(root, path).replaceAll('\\', '/');

function geometry(file) {
  const path = join(svgFolder, file);
  const svg = readFileSync(path, 'utf8');
  const fail = (reason) => {
    throw new Error(`${shown(path)} ${reason}`);
  };
  const start = /<svg\b[^>]*>/.exec(svg)?.[0] ?? fail('has no svg element.');
  const attribute = (name) => new RegExp(`\\s${name}\\s*=\\s*"([^"]*)"`).exec(start)?.[1];
  if (attribute('width') !== '16' || attribute('height') !== '16' || (attribute('viewBox') ?? '0 0 16 16') !== '0 0 16 16') {
    fail('is not 16 by 16.');
  }
  if (/evenodd/.test(svg)) {
    fail('fills even-odd, and the generated geometry fills nonzero.');
  }
  if (/\btransform\s*=/.test(svg)) {
    fail('has a transform, which the generator does not apply.');
  }
  const other = [...svg.matchAll(/<([A-Za-z][\w:-]*)/g)].map((match) => match[1]).find((name) => name !== 'svg' && name !== 'path');
  if (other) {
    fail(`has a <${other}> element, and only <path> elements become geometry.`);
  }
  const paths = [...svg.matchAll(/<path\b[^>]*\sd="([^"]*)"/g)].map((match) => match[1]);
  if (paths.length === 0) {
    fail('has no path.');
  }
  return `F1 ${paths.join(' ')}`;
}

function generate(manifest) {
  return [
    '<!-- Generated by scripts/fluent-icons.mjs from the SVGs in scripts/icons/fluent. Edit scripts/icons/fluent-icons.json and rerun it. -->',
    `<!-- Fluent UI System Icons by Microsoft at commit ${manifest.commit}, MIT License, Copyright (c) 2020 Microsoft Corporation. THIRD-PARTY-NOTICES.md holds the license. -->`,
    '<ResourceDictionary xmlns="https://github.com/avaloniaui"',
    '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    ...manifest.icons.map(({ key, file }) => `  <StreamGeometry x:Key="${key}">${geometry(file)}</StreamGeometry>`),
    '</ResourceDictionary>',
    '',
  ].join('\n');
}

// C# names some keys in strings, such as a node kind's icon, and a missing key fails at run time rather than at build.
const usePatterns = [
  [/\.(axaml|xaml)$/, /(?:StaticResource|DynamicResource)\s+(?:ResourceKey\s*=\s*)?["']?(Icon[A-Z]\w*)/g],
  [/\.cs$/, /"(Icon[A-Z]\w*)"/g],
];

function* sourceFiles(folder) {
  for (const entry of readdirSync(folder, { withFileTypes: true })) {
    const path = join(folder, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== 'bin' && entry.name !== 'obj') {
        yield* sourceFiles(path);
      }
    } else if (usePatterns.some(([kind]) => kind.test(path))) {
      yield path;
    }
  }
}

function missingKeys(manifest) {
  const keys = new Set(manifest.icons.map(({ key }) => key));
  const missing = [];
  for (const path of sourceFiles(desktop)) {
    const [, pattern] = usePatterns.find(([kind]) => kind.test(path));
    readFileSync(path, 'utf8')
      .split('\n')
      .forEach((line, index) => {
        for (const [, key] of line.matchAll(pattern)) {
          if (!keys.has(key)) {
            missing.push(`  ${shown(path)}:${index + 1}: ${key}`);
          }
        }
      });
  }
  return missing;
}

// raw.githubusercontent.com serves files without the GitHub API's limit of 60 requests an hour.
async function fetchMissing(manifest) {
  const base = `https://raw.githubusercontent.com/microsoft/fluentui-system-icons/${manifest.commit}`;
  const files = [
    ['LICENSE', `${base}/LICENSE`],
    ...manifest.icons.map(({ asset, file }) => [file, `${base}/assets/${encodeURIComponent(asset)}/SVG/${file}`]),
  ];
  mkdirSync(svgFolder, { recursive: true });
  for (const [file, url] of files) {
    const path = join(svgFolder, file);
    if (existsSync(path)) {
      continue;
    }
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`${url} answered ${response.status}.`);
    }
    writeFileSync(path, await response.text());
    console.log(`Fetched ${shown(path)}.`);
  }
}

try {
  const manifest = JSON.parse(readFileSync(manifestFile, 'utf8'));
  if (mode === '--check') {
    let current = '';
    try {
      current = readFileSync(output, 'utf8').replaceAll('\r\n', '\n');
    } catch {}
    const problems = [];
    if (current !== generate(manifest)) {
      problems.push(`${shown(output)} is stale. Run node scripts/fluent-icons.mjs.`);
    }
    const missing = missingKeys(manifest);
    if (missing.length > 0) {
      problems.push(`These icon keys have no entry in ${shown(manifestFile)}:`, ...missing);
    }
    if (problems.length > 0) {
      console.error(problems.join('\n'));
      process.exit(1);
    }
    console.log('FluentIcons.axaml is current, and the manifest holds every icon key the desktop app uses.');
  } else {
    if (mode === '--fetch') {
      await fetchMissing(manifest);
    }
    writeFileSync(output, generate(manifest));
    console.log(`Wrote ${shown(output)}.`);
  }
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
