import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { after, test } from 'node:test';

const script = path.join(import.meta.dirname, 'fluent-icons.mjs');
const svg = (body, size = 'width="16" height="16" viewBox="0 0 16 16"') =>
  `<svg ${size} fill="none" xmlns="http://www.w3.org/2000/svg">\n${body}\n</svg>\n`;
const play = svg('<path d="M4 3V13L14 8Z" fill="#212121"/>');
const roots = [];
after(() => roots.forEach((root) => fs.rmSync(root, { recursive: true, force: true })));

// icons maps each key to its SVG text, and sources maps a path under src/IDevelop.Desktop to its text.
function project({ icons = { IconRun: play }, sources = {} } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'fluent-icons-'));
  roots.push(root);
  const folder = path.join(root, 'scripts', 'icons', 'fluent');
  fs.mkdirSync(folder, { recursive: true });
  fs.mkdirSync(path.join(root, 'src', 'IDevelop.Desktop', 'Theme'), { recursive: true });
  const entries = Object.entries(icons).map(([key, text]) => {
    const file = `ic_fluent_${key.toLowerCase()}_16_filled.svg`;
    fs.writeFileSync(path.join(folder, file), text);
    return { key, asset: key.slice(4), file };
  });
  fs.writeFileSync(path.join(root, 'scripts', 'icons', 'fluent-icons.json'), JSON.stringify({ commit: 'abc123', icons: entries }));
  for (const [name, text] of Object.entries(sources)) {
    const file = path.join(root, 'src', 'IDevelop.Desktop', name);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text);
  }
  return root;
}

function run(root, ...args) {
  const result = spawnSync(process.execPath, [script, ...args, root], { encoding: 'utf8' });
  return { status: result.status, out: result.stdout.trim(), err: result.stderr.trim() };
}

const generated = (root) => {
  const file = path.join(root, 'src', 'IDevelop.Desktop', 'Theme', 'FluentIcons.axaml');
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : undefined;
};

test('writes one nonzero geometry per icon, joining the paths of each file', () => {
  const root = project({
    icons: {
      IconRun: play,
      IconTwo: svg('<path d="M1 1H3V3Z" fill="#212121"/>\n<path d="M5 5H7V7Z" fill="#212121"/>'),
    },
  });

  const result = run(root);

  assert.equal(result.status, 0);
  assert.equal(result.out, 'Wrote src/IDevelop.Desktop/Theme/FluentIcons.axaml.');
  assert.equal(
    generated(root),
    [
      '<!-- Generated by scripts/fluent-icons.mjs from the SVGs in scripts/icons/fluent. Edit scripts/icons/fluent-icons.json and rerun it. -->',
      '<!-- Fluent UI System Icons by Microsoft at commit abc123, MIT License, Copyright (c) 2020 Microsoft Corporation. THIRD-PARTY-NOTICES.md holds the license. -->',
      '<ResourceDictionary xmlns="https://github.com/avaloniaui"',
      '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
      '  <StreamGeometry x:Key="IconRun">F1 M4 3V13L14 8Z</StreamGeometry>',
      '  <StreamGeometry x:Key="IconTwo">F1 M1 1H3V3Z M5 5H7V7Z</StreamGeometry>',
      '</ResourceDictionary>',
      '',
    ].join('\n'),
  );
});

for (const [name, icon, reason] of [
  ['an icon that is not 16 by 16', svg('<path d="M4 3V13L14 8Z"/>', 'width="20" height="20" viewBox="0 0 20 20"'), 'is not 16 by 16.'],
  ['an even-odd fill', svg('<path fill-rule="evenodd" clip-rule="evenodd" d="M4 3V13L14 8Z"/>'), 'fills even-odd, and the generated geometry fills nonzero.'],
  ['a transform', svg('<path transform="translate(1 0)" d="M4 3V13L14 8Z"/>'), 'has a transform, which the generator does not apply.'],
  ['a shape that is not a path', svg('<circle cx="8" cy="8" r="6"/>'), 'has a <circle> element, and only <path> elements become geometry.'],
]) {
  test(`fails on ${name} and writes nothing`, () => {
    const root = project({ icons: { IconRun: play, IconBad: icon } });

    const result = run(root);

    assert.equal(result.status, 1);
    assert.equal(result.err, `scripts/icons/fluent/ic_fluent_iconbad_16_filled.svg ${reason}`);
    assert.equal(generated(root), undefined);
  });
}

test('--check passes on a current file and fails once an icon changes', () => {
  const root = project();
  run(root);

  assert.deepEqual(run(root, '--check'), {
    status: 0,
    out: 'FluentIcons.axaml is current, and the manifest holds every icon key the desktop app uses.',
    err: '',
  });

  fs.writeFileSync(path.join(root, 'scripts', 'icons', 'fluent', 'ic_fluent_iconrun_16_filled.svg'), svg('<path d="M4 4V12L12 8Z"/>'));

  const stale = run(root, '--check');
  assert.equal(stale.status, 1);
  assert.equal(stale.err, 'src/IDevelop.Desktop/Theme/FluentIcons.axaml is stale. Run node scripts/fluent-icons.mjs.');
});

test('--check names every icon key that XAML or a C# string uses without a manifest entry', () => {
  const root = project({
    sources: {
      'Canvas/Card.axaml': [
        '<PathIcon Data="{StaticResource IconRun}" />',
        '<PathIcon Data="{StaticResource IconGone}" /> <PathIcon Data="{DynamicResource IconAlsoGone}" />',
        '<PathIcon Data="{StaticResource ResourceKey=IconKeyed}" /> <PathIcon Data="{StaticResource PlusIcon}" />',
      ].join('\n'),
      'Canvas/NodeKind.cs': 'Info(Kind.Run, "IconRun"); Info(Kind.Review, "IconKindReview"); var label = "Icon";',
      'bin/Release/Copy.cs': '"IconInBuildOutput"',
    },
  });
  run(root);

  const result = run(root, '--check');

  assert.equal(result.status, 1);
  assert.deepEqual(result.err.split('\n').sort(), [
    '  src/IDevelop.Desktop/Canvas/Card.axaml:2: IconAlsoGone',
    '  src/IDevelop.Desktop/Canvas/Card.axaml:2: IconGone',
    '  src/IDevelop.Desktop/Canvas/Card.axaml:3: IconKeyed',
    '  src/IDevelop.Desktop/Canvas/NodeKind.cs:1: IconKindReview',
    'These icon keys have no entry in scripts/icons/fluent-icons.json:',
  ]);
});
